from typing import Any

class _SourceAnalysisSession:
    def __init__(
        self,
        text: Any,
        *,
        dialect: Any = None,
        external_calls: Any = None,
    ) -> None: ...
    def backward_slice(self, /, function, node, *, function_id=None) -> Any: ...
    def call_summaries(self, /) -> Any: ...
    def control_flow_graphs(self, /) -> Any: ...
    def data_flow(self, /) -> Any: ...
    @property
    def diagnostics(self) -> Any: ...
    @property
    def dialect(self) -> Any: ...
    def export_graphs(self, /, repr, format) -> Any: ...
    @property
    def external_calls(self) -> Any: ...
    def native_graphs(self, /, *, repr="cfg") -> Any: ...
    def query_reaches(self, /, source, parameter, sink) -> Any: ...
    def query_reaches_by_id(
        self,
        /,
        source_function_id,
        parameter,
        sink_function_id,
    ) -> Any: ...
    @property
    def source(self) -> Any: ...
    @property
    def source_id(self) -> Any: ...

class _SourceNativeGraph:
    @property
    def analysis_revision(self) -> Any: ...
    def ancestors(self, /, node) -> Any: ...
    def descendants(self, /, node) -> Any: ...
    @property
    def directed(self) -> Any: ...
    @property
    def edge_count(self) -> Any: ...
    def edge_list(self, /) -> Any: ...
    def edges(self, /) -> Any: ...
    @property
    def external_call_policy(self) -> Any: ...
    @property
    def function_id(self) -> Any: ...
    @property
    def graph_kind(self) -> Any: ...
    def in_degree(self, /, node) -> Any: ...
    @property
    def input_dialect(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def node_count(self) -> Any: ...
    def nodes(self, /) -> Any: ...
    def out_degree(self, /, node) -> Any: ...
    def predecessors(self, /, node) -> Any: ...
    @property
    def representation(self) -> Any: ...
    @property
    def source_id(self) -> Any: ...
    def successors(self, /, node) -> Any: ...

class _Source:
    AnalysisSession: type[_SourceAnalysisSession]
    NativeGraph: type[_SourceNativeGraph]
    @staticmethod
    def analyze(text: Any) -> Any: ...
    @staticmethod
    def backward_slice(
        text: Any,
        function: Any,
        node: Any,
        *,
        source_id: Any = None,
        function_id: Any = None,
        graph_kind: Any = None,
        analysis_revision: Any = None,
    ) -> Any: ...
    @staticmethod
    def call_summaries(text: Any) -> Any: ...
    @staticmethod
    def control_dependence(text: Any) -> Any: ...
    @staticmethod
    def control_flow_graphs(text: Any) -> Any: ...
    @staticmethod
    def data_flow(text: Any) -> Any: ...
    @staticmethod
    def export_choices() -> Any: ...
    @staticmethod
    def export_graphs(text: Any, repr: Any, format: Any) -> Any: ...
    @staticmethod
    def feature_names() -> Any: ...
    @staticmethod
    def features(text: Any) -> Any: ...
    @staticmethod
    def functions(text: Any) -> Any: ...
    @staticmethod
    def native_graphs(text: Any, *, repr: Any = "cfg") -> Any: ...
    @staticmethod
    def normalize(text: Any, dialect: Any) -> Any: ...
    @staticmethod
    def query_reaches(text: Any, source: Any, parameter: Any, sink: Any) -> Any: ...
    @staticmethod
    def query_reaches_by_id(
        text: Any,
        source_function_id: Any,
        parameter: Any,
        sink_function_id: Any,
    ) -> Any: ...
    @staticmethod
    def reaches(text: Any, source: Any, parameter: Any, sink: Any) -> Any: ...

class _CSource:
    @staticmethod
    def is_scoreable_name(name: Any) -> Any: ...
    @staticmethod
    def parity_cfgs(text: Any) -> Any: ...

__version__: str
source: _Source
csource: _CSource
