from typing import Any

class _Source:
    def analyze(self, *args: Any, **kwargs: Any) -> Any: ...
    def backward_slice(self, *args: Any, **kwargs: Any) -> Any: ...
    def call_summaries(self, *args: Any, **kwargs: Any) -> Any: ...
    def control_dependence(self, *args: Any, **kwargs: Any) -> Any: ...
    def control_flow_graphs(self, *args: Any, **kwargs: Any) -> Any: ...
    def data_flow(self, *args: Any, **kwargs: Any) -> Any: ...
    def export_choices(self, *args: Any, **kwargs: Any) -> Any: ...
    def export_graphs(self, *args: Any, **kwargs: Any) -> Any: ...
    def feature_names(self, *args: Any, **kwargs: Any) -> Any: ...
    def features(self, *args: Any, **kwargs: Any) -> Any: ...
    def functions(self, *args: Any, **kwargs: Any) -> Any: ...
    def normalize(self, *args: Any, **kwargs: Any) -> Any: ...
    def reaches(self, *args: Any, **kwargs: Any) -> Any: ...

class _CSource:
    def is_scoreable_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def parity_cfgs(self, *args: Any, **kwargs: Any) -> Any: ...

source: _Source
csource: _CSource
